# Generated by Django 6.0 on 2026-01-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'course', 'date')},
        ),
    ]
