# Generated by Django 6.0 on 2026-01-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_attendancerecord_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
