# Generated by Django 6.0 on 2026-01-03 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_teacher_department_teacher_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AddField(
            model_name='teacher',
            name='dept',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
