# Generated by Django 6.0 on 2026-01-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_teacher_department_teacher_dept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
