# Generated by Django 6.0 on 2026-01-03 09:42

import management.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_teacher_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', management.models.CustomUserManager()),
            ],
        ),
    ]
